import {
  WHITE,
  BLACK,
  RED_900,
  RED_800,
  RED_700,
  RED_600,
  RED,
  RED_400,
  RED_300,
  RED_200,
  RED_100,
  RED_030,
  BLUE_900,
  BLUE_800,
  BLUE_700,
  BLUE_600,
  BLUE,
  BLUE_400,
  BLUE_300,
  BLUE_200,
  BLUE_100,
  BLUE_030,
  GREEN_900,
  GREEN_800,
  GREEN_700,
  GREEN_600,
  GREEN,
  GREEN_400,
  GREEN_300,
  GREEN_200,
  GREEN_100,
  GREEN_030,
  ORANGE_900,
  ORANGE_800,
  ORANGE_700,
  ORANGE_600,
  ORANGE,
  ORANGE_400,
  ORANGE_300,
  ORANGE_200,
  ORANGE_100,
  ORANGE_030,
  RED_DARKER_900,
  RED_DARKER_800,
  RED_DARKER_700,
  RED_DARKER_600,
  RED_DARKER,
  RED_DARKER_400,
  RED_DARKER_300,
  RED_DARKER_200,
  RED_DARKER_100,
  RED_DARKER_030,
  GRAY_900,
  GRAY_800,
  GRAY_700,
  GRAY_600,
  GRAY,
  GRAY_400,
  GRAY_300,
  GRAY_200,
  GRAY_100,
  GRAY_030,
  GRAY_020,
  BLUEFB,
  GOOGLE,
  YELLOW,
  GRAY_INACTIVE,
  GRAY_DISABLED,
  GRAY_BG,
  GRAY_BORDER,
  GRAY_CONTROL_BORDER,
  GRAY_NATIVE,
  ORANGE_ALERT,
  GREEN_SUCCESS,
} from './BaseColors';

export const RED_PRESSED = RED_700;

export const PIERED = RED;
export const PIEBLUE = BLUE;
export const PIEGREEN = GREEN;
export const BORDERCOLOR = GRAY_BORDER;

export const PROGRESSBAR_RED = RED;
export const PROGRESSBAR_BLUE = BLUE;
export const PROGRESSBAR_GREEN = GREEN;
export const PROGRESSBAR_YELLOW = YELLOW;
export const PROGRESSBAR_ORANGE = ORANGE;

export const TOOLTIP_DARK = GRAY_600;
export const TOAST_SUCCESS_STICKY = BLUE_100;
export const TOAST_DANGER_STICKY = RED_100;
export const TOAST_SUCCESS = GREEN_100;

export const ICON_ALERT = ORANGE_ALERT;
export const ICON_SUCCESS = GREEN_SUCCESS;

export const ACTIONBAR_BORDER = 'rgba(191, 191, 191, 0.5)';
export const ACTIONBAR_TAG = GRAY;
export const TABS_INACTIVE_BORDER = GRAY_300;

export const GRAY_CHECKBOX_DEFAULT_BG = GRAY_030;
export const GRAY_CHECKBOX_BORDER = GRAY_CONTROL_BORDER;

export const GRAY_RADIOBUTTON_DEFAULT_BG = GRAY_030;
export const GRAY_RADIOBUTTON_BORDER = GRAY_CONTROL_BORDER;

export const GRAY_SWITCHER_TEXT = GRAY_400;
export const GRAY_SWITCHER_BG = GRAY_200;

export const GRAY_SWAP_BG = GRAY_NATIVE;
export const GRAY_SWAP_BORDER = GRAY_BORDER;

export const AVATAR_BG_DEFAULT = '#929292';
export const AVATAR_BG_MALE = '#759dce';
export const AVATAR_BG_FEMALE = '#efb3cc';

export const DOT_ACTIVE = RED;
export const DOT_INACTIVE = GRAY_INACTIVE;
export const DOT_BORDER = RED;

export const PAGINATINATON_ACTIVE = RED;
export const PAGINATINATON_INACTIVE = GRAY_INACTIVE;

export const DRAGBAR_GRAY = GRAY_100;

export const COUNTER_BG_DISABLED = GRAY_020;
export const COUNTER_BORDER = GRAY_DISABLED;
export const COUNTER_ICON = BLACK;
export const COUNTER_ICON_DISABLED = GRAY_200;

export const TEXTINPUT_LABEL_GRAY = GRAY_400;
export const TEXTINPUT_BOTTOM_BORDER = GRAY_300;
export const TEXTINPUT_DISABLE_GRAY = GRAY_300;
export const TEXTINPUT_CLOSE_BUTTON = GRAY_300;

export const LIST_BOTTOM_COLOR = GRAY_SWITCHER_BG;
export const LIST_SUBTITLE_COLOR = GRAY_SWITCHER_TEXT;
export const LIST_INACTIVE_BACKGROUND = GRAY_030;

export const PROGRESSBAR_QUOTA_BACKGROUND = GRAY_100;
export const PROGRESSBAR_QUOTA_FOREGROUND = '#ff4e81';

export const DISABLED_GREY = GRAY_030;
export const RANK_BG = GRAY_BG;
export const INACTIVE_MONTH_STEP = GRAY_100;
export const CARD_BANNER_GRAY = GRAY_100;
